rog_map:
  ros_callback:
    enable: true
    cloud_topic: /cloud_registered
    odom_topic: /kiss/odometry
    odom_timeout: 2.0

  visualization:
    enable: true
    frame_id: odom
    time_rate: 2.0
    frame_rate: 0
    range: [30.0, 30.0, 6.0]
    pub_unknown_map_en: false
    use_dynamic_reconfigure: false

  esdf:
    enable: true
    resolution: 0.20
    local_update_box: [20.0, 20.0, 4.0]

  load_pcd_en: false
  map_sliding:
    enable: true
    threshold: 2.0
  fix_map_origin: [0.0, 0.0, 0.0]
  frontier_extraction_en: false

  resolution: 0.20
  inflation_resolution: 0.20
  inflation_step: 1
  unk_inflation_en: false
  unk_inflation_step: 1
  intensity_thresh: -1
  map_size: [40.0, 40.0, 8.0]
  point_filt_num: 2
  virtual_ground_height: -2.0
  virtual_ceil_height: 4.0

  raycasting:
    enable: true
    batch_update_size: 1
    unk_thresh: 0.70
    p_hit: 0.70
    p_miss: 0.70
    p_min: 0.12
    p_max: 0.97
    p_occ: 0.80
    p_free: 0.30
    ray_range: [0.5, 25.0]
    local_update_box: [30.0, 30.0, 6.0]
